
export const cars = [
    {
        brand: 'Audi',
        model: 'A6',
        power: 150,
        year: 2018,
        price: 189900,
        mileage: 67000,
        fuel: 'Diesel',
        capacity: '2 998',
        city: 'Kraków',
        img: "img/audiA6.jpg",
        bodyType: 'Kombi'
    },
    {
        brand: 'BMW',
        model: 'Seria 5',
        power: 272,
        year: 2020,
        price: 260000,
        mileage: 9069,
        fuel: 'Diesel',
        capacity: '2 996',
        city: 'Poznań' ,
        img: "img/pexels-mike-b-170811.jpg",
        bodyType: 'Sedan'
    },
     {
        brand: 'Alfa Romeo',
        model: '4c',
        power: 250,
        year: 2014,
        price: 129900,
        mileage: 59000,
        fuel: 'Benzyna',
        capacity: '1 648',
        city: 'Zabrze',
        img: "img/alfa.jpg",
        bodyType: 'Coupe'
    },
     {
        brand: 'Mercedes Benz', 
        model: 'Klasa A',
        power: 131,
        year: 2014,
        price: 59900,
        mileage: 59000,
        fuel: 'Diesel',
        capacity: '1 998',
        city: 'Kraków',
        img:  "img/merc.jpg",
        bodyType: 'Kompakt'
    },
     {
        brand: 'BMW',
        model: 'Seria 3',
        power: 143,
        year: 2010,
        price: 79000,
        mileage: 200000,
        fuel: 'Benzyna + LPG',
        capacity: '2 996',
        city: 'Brzesko',
        img:  "img/bmw3coupe.jpg",
        bodyType: 'Coupe'
    },
     {
        brand: 'Maserati',
        model: 'GranTurismo',
        power: 442,
        year: 2008,
        price: 130000,
        mileage: 167000,
        fuel: 'Benzyna',
        capacity: '3 998',
        city: 'Szczecin',
        img: "img/maserati.jpg",
        bodyType: 'Coupe'
    },
     {
        brand: 'BMW',
        model: 'Seria 4',
        power: 272,
        year: 2016,
        price: 150000,
        mileage: 100000,
        fuel: 'Benzyna',
        capacity: '1 998',
        city: 'Gniezno',
        img: "img/BMWseria4.jpg",
        bodyType: 'Coupe'
    },
     {
        brand: 'Chevrolet',
        model: 'Camaro',
        power: 500,
        year: 2012,
        price: 99999,
        mileage: 88652,
        fuel: 'Benzyna',
        capacity: '6 188',
        city: 'Warszawa',
        img:  "img/camaro.jpg",
        bodyType: 'Coupe' 
    },
     {
        brand: 'Ford',
        model: 'Focus',
        power: 90,
        year: 2014,
        price: 19999,
        mileage: 220000,
        fuel: 'Diesel',
        capacity: '1618',
        city: 'Gdańsk',
        img: 'img/ford.jpg',
        bodyType: 'Kompakt'
    },
     {
        brand: 'Peugeot',
        model: '107',
        power: 60,
        year: 2010,
        price: 12000,
        mileage: 144000,
        fuel: 'Benzyna',
        capacity: '998',
        city: 'Białystok',
        img: 'imgCarsBack/peugeot107.jpg',
        bodyType: 'Auta miejskie'
    },
     {
        brand: 'Alfa Romeo',
        model: '159',
        power: 150,
        year: 2008,
        price: 19000,
        mileage: 199999,
        fuel: 'Diesel',
        capacity: '1 996',
        city: 'Toruń',
        img: 'imgCarsBack/alfa159.jpg',
        bodyType: 'Sedan'
    },
     {
        brand: 'Alfa Romeo',
        model: 'Giulia',
        power: 200,
        year: 2020,
        price: 130000,
        mileage: 33000,
        fuel: 'Benzyna',
        capacity: '1 998',
        city: 'Wrocław',
        img: 'imgCarsBack/alfagiulia.jpg',
        bodyType: 'Sedan'
    },
     {
        brand: 'Alfa Romeo',
        model: 'Giulia',
        power: 200,
        year: 2017,
        price: 100000,
        mileage: 120000,
        fuel: 'Diesel',
        capacity: '1 996',
        city: 'Kraków',
        img: 'imgCarsBack/alfagiulia2.jpg',
        bodyType: 'Sedan'
    },
     {
        brand: 'Alfa Romeo',
        model: 'Giulia',
        power: 572,
        year: 2020,
        price: 299900,
        mileage: 19500,
        fuel: 'Benzyna',
        capacity: '2 796',
        city: 'Warszawa',
        img: 'imgCarsBack/alfagiulia3.jpg',
        bodyType: 'Sedan'
    },
     {
        brand: 'Alfa Romeo',
        model: 'Mito',
        power: 100,
        year: 2011,
        price: 16000,
        mileage: 185000,
        fuel: 'Benzyna',
        capacity: '1 360',
        city: 'Kielce',
        img: 'imgCarsBack/alfamito.jpg',
        bodyType: 'Auta miejskie'
    },
     {
        brand: 'Alfa Romeo',
        model: 'Mito',
        power: 80,
        year: 2012,
        price: 14500,
        mileage: 220000,
        fuel: 'Diesel',
        capacity: '1360',
        city: 'Łódź',
        img: 'imgCarsBack/alfaromeomito.jpg',
        bodyType: 'Auta miejskie'
    },
     {
        brand: 'Audi',
        model: 'A3',
        power: 150,
        year: 2002,
        price: 9999,
        mileage: 260000,
        fuel: 'Benzyna',
        capacity: '1 800',
        city: 'Lublin',
        img: 'imgCarsBack/audia3.jpg',
        bodyType: 'Kompakt'
    },
     {
        brand: 'Audi',
        model: 'A5',
        power: 212,
        year: 2014,
        price: 90000,
        mileage: 200000,
        fuel: 'Diesel',
        capacity: '2 996',
        city: 'Warszawa',
        img: 'imgCarsBack/audiA5.jpg',
        bodyType: 'Sedan'
    },
     {
        brand: 'BMW',
        model: 'Seria 3',
        power: 192,
        year: 2006,
        price: 24000,
        mileage: 232500,
        fuel: 'Benzyna + LPG',
        capacity: '2 458',
        city: 'Toruń',
        img: 'imgCarsBack/bmwseria3.jpg',
        bodyType: 'Sedan'
    },
     {
        brand: 'Citroen',
        model: 'C3',
        power: 80,
        year: 2007,
        price: 8900,
        mileage: 178000,
        fuel: 'Benzyna',
        capacity: '1 600',
        city: 'Kraków',
        img: 'imgCarsBack/Citroen-C3.jpg',
        bodyType: 'Kompakt'
    },
     {
        brand: 'Honda',
        model: 'Civic',
        power: 140,
        year: 2007,
        price: 22900,
        mileage: 230000,
        fuel: 'Benzyna + LPG',
        capacity: '1 628',
        city: 'Sandomierz',
        img: 'imgCarsBack/civic.webp',
        bodyType: 'Kompakt'
    },
     {
        brand: 'Fiat',
        model: 'Punto',
        power: 60,
        year: 2002,
        price: 5800,
        mileage: 220000,
        fuel: 'Benzyna',
        capacity: '1 224',
        city: 'Kraków',
        img: 'imgCarsBack/FiatPunto.jpg',
        bodyType: 'Auta miejskie'
    },
     {
        brand: 'Fiat',
        model: 'Punto',
        power: 75,
        year: 2008,
        price: 12900,
        mileage: 189000,
        fuel: 'Diesel',
        capacity: '1 400',
        city: 'Rzeszów',
        img: 'imgCarsBack/Fiat_punto.jpg',
        bodyType: 'Kompakt'
    },
     {
        brand: 'Fiat',
        model: 'Punto',
        power: 60,
        year: 2001,
        price: 4900,
        mileage: 184498,
        fuel: 'Benzyna',
        capacity: '1 224',
        city: 'Opole',
        img: 'imgCarsBack/FiatPunto2.jpg',
        bodyType: 'Auta małe'
    },
     {
        brand: 'Fiat',
        model: 'Punto',
        power: 75,
        year: 2009,
        price: 13000,
        mileage: 210000,
        fuel: 'Benzyna + LPG',
        capacity: '1 400',
        city: 'Warszawa',
        img: 'imgCarsBack/FiatPunto3.jpg',
        bodyType: 'Kompakt'
    },
     {
        brand: 'Nissan',
        model: 'GTR',
        power: 510,
        year: 2014,
        price: 270000,
        mileage: 55400,
        fuel: 'Benzyna',
        capacity: '3 799',
        city: 'Opole',
        img: 'imgCarsBack/Nissan-GT-R.jpg',
        bodyType: 'Coupe'
    },
     {
        brand: 'Nissan',
        model: 'GTR',
        power: 510,
        year: 2015,
        price: 235000,
        mileage: 79000,
        fuel: 'Benzyna',
        capacity: '3 799',
        city: 'Chorzów',
        img: 'imgCarsBack/nissangtr.jpg',
        bodyType: 'Coupe'
    },
     {
        brand: 'Peugeot',
        model: '107',
        power: 60,
        year: 2010,
        price: 10000,
        mileage: 145000,
        fuel: 'Benzyna',
        capacity: '998',
        city: 'Radom',
        img: 'imgCarsBack/peugeot1072.jpg',
        bodyType: 'Auta miejskie'
    },
     {
        brand: 'Fiat',
        model: 'Punto',
        power: 60,
        year: 2001,
        price: 6600,
        mileage: 229900,
        fuel: 'Benzyna',
        capacity: '1 224',
        city: 'Nowy Sącz',
        img: 'imgCarsBack/punto2.jpeg',
        bodyType: 'Auta miejskie'
    },
     {
        brand: 'Renault',
        model: 'Clio',
        power: 118,
        year: 2013,
        price: 29000,
        mileage: 155000,
        fuel: 'Benzyna',
        capacity: '1 149',
        city: 'Kraków',
        img: 'imgCarsBack/renault-clio-iv.jpg',
        bodyType: 'Auta miejskie'
    },
     {
        brand: 'Renault',
        model: 'Clio',
        power: 115,
        year: 2017,
        price: 37700,
        mileage: 124500,
        fuel: 'Diesel',
        capacity: '1 161',
        city: 'Gliwice',
        img: 'imgCarsBack/renaultClio.jpg',
        bodyType: 'Auta miejskie'
    },
    {
       brand: 'Seat',
       model: 'Ibiza',
       power: 64,
       year: 2004,
       price: 4899,
       mileage: 245000,
       fuel: 'Benzyna',
       capacity: '1 198',
       city: 'Biała Podlaska',
       img: 'imgCarsBack/Seat-Ibiza-1.6.jpg',
       bodyType: 'Auta miejskie'
   },
   {
      brand: 'Skoda',
      model: 'Octavia',
      power: 120,
      year: 2005,
      price: 12800,
      mileage: 230000,
      fuel: 'Diesel',
      capacity: '1 896',
      city: 'Poznań',
      img: 'imgCarsBack/skodaoctavia.jpg',
      bodyType: 'Sedan'
  },
  {
     brand: 'Subaru',
     model: 'Impreza',
     power: 225,
     year: 2004,
     price: 89900,
     mileage: 17200,
     fuel: 'Benzyna',
     capacity: '1 998',
     city: 'Kołobrzeg',
     img: 'imgCarsBack/Subaruimpreza.jpg',
     bodyType: 'Sedan'
 },
 {
    brand: 'Suzuki',
    model: 'Swift',
    power: 92,
    year: 2005,
    price: 14900,
    mileage: 190000,
    fuel: 'Benzyna',
    capacity: '1 300',
    city: 'Legnica',
    img: 'imgCarsBack/Suzuki-Swift-V.jpg',
    bodyType: 'Auta miejskie'
},
{
    brand: 'Suzuki',
    model: 'Swift',
    power: 75,
    year: 2007,
    price: 12000,
    mileage: 200000,
    fuel: 'Diesel',
    capacity: '1 300',
    city: 'Katowice',
    img: 'imgCarsBack/suzukiswift.jpg',
    bodyType: 'Auta miejskie'
},
{
   brand: 'Toyota',
   model: 'Yaris',
   power: 75,
   year: 2013,
   price: 36900,
   mileage: 115000,
   fuel: 'Hybryda',
   capacity: '1 500',
   city: 'Katowice',
   img: 'imgCarsBack/Toyota-Yaris.jpg',
   bodyType: 'Auta miejskie'
},
{
    brand: 'Toyota',
    model: 'Supra',
    power: 280,
    year: 1997,
    price: 250000,
    mileage: 168000,
    fuel: 'Benzyna',
    capacity: '2 997',
    city: 'Częstochowa',
    img: 'imgCarsBack/toyotasupra.jpg',
    bodyType: 'Coupe'
},
{
   brand: 'Volkswagen',
   model: 'Golf',
   power: 85,
   year: 2010,
   price: 19700,
   mileage: 210000,
   fuel: 'Benzyna',
   capacity: '1 197',
   city: 'Koszalin',
   img: 'imgCarsBack/VW_Golf_VI.jpg',
   bodyType: 'Kompakt'
},
{
    brand: 'Volkswagen',
   model: 'Passat',
   power: 115,
   year: 2004,
   price: 9800,
   mileage: 262200,
   fuel: 'Diesel',
   capacity: '1 896',
   city: 'Rzeszów',
   img: 'imgCarsBack/VW_Passat_B5.jpg',
   bodyType: 'Sedan'
},
{
    brand: 'Volkswagen',
   model: 'Golf',
   power: 85,
   year: 2003,
   price: 7900,
   mileage: 278000,
   fuel: 'Diesel',
   capacity: '1 896',
   city: 'Szczecin',
   img: 'imgCarsBack/vwgolf.jpeg',
   bodyType: 'Kompakt'
},
{
    brand: 'Volkswagen',
   model: 'Passat',
   power: 105,
   year: 2003,
   price: 8000,
   mileage: 249000,
   fuel: 'Diesel',
   capacity: '1 896',
   city: 'Suwałki',
   img: 'imgCarsBack/vwpassat.jpg',
   bodyType: 'Sedan'
},
{
    brand: 'Toyota',
    model: 'Yaris',
    power: 86,
    year: 2002,
    price: 7900,
    mileage: 215000,
    fuel: 'Benzyna + LPG',
    capacity: '1 300',
    city: 'Zamość',
    img: 'imgCarsBack/yaris.jpeg',
    bodyType: 'Auta małe'
},

]